# Generated by Django 6.0.5 on 2026-05-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0003_emailverification_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_code',
        ),
    ]
