# Generated by Django 6.0.5 on 2026-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0004_remove_userprofile_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='expertise_field',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
