# Generated by Django 6.0.5 on 2026-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0005_userprogress_expertise_field_userprogress_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='asked_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='batch_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='question_batch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='expertise_field',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
