# Generated by Django 6.0.5 on 2026-06-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0006_userprogress_asked_topics_userprogress_batch_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expertise_field',
            field=models.CharField(default='Full Stack Developer', max_length=100),
        ),
    ]
